export const SHOW_LOADER = 'SHOW_LOADER'
export const CATCH_ERROR = 'CATCH_ERROR'
export const FETCH_CURRENT_PRICE = 'FETCH_CURRENT_PRICE'

export const FETCH_TRADES_SUCCESS = 'FETCH_TRADES_SUCCESS'
export const FETCH_TRADE_SUCCESS = 'FETCH_TRADE_SUCCESS'
export const CLOSE_SELECTED_TRADE = 'CLOSE_SELECTED_TRADE'

export const READ_MESSAGES = 'READ_MESSAGES'
export const UNREAD_MESSAGES = 'UNREAD_MESSAGES'

export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS'
export const POST_MESSAGE = 'POST_MESSAGE'
export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS'
export const CLEAR_MESSAGES_SUCCESS = 'CLEAR_MESSAGES_SUCCESS'
